[workspace]
members = [
    "monk", 
    "monk-types", 
    "monk-sqlite", 
    "monk-index", 
    "monk-dl",
    "monk-summary",
    "apps/monk-cli", 
    "apps/monk-egui", 
    "apps/monk-server",
    "apps/monk-desktop"
]